### ISSUE TITLE
Encrypt key issues

### ISSUE THREAD

**Issue by vacquah** [chrisvanmeer/at-hashi-demo#3]
Hello, in the consul.hcl.j2 I am getting error messages related to : encrypt = "{{ consul_ecryption_key }}" . Is this a typo with the spelling of "encryption" instead of "ecryption" as shown above?  I changed it but still got errors when running 03_consul-deployment.yml. the deployment failed.  

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleUndefinedVariable: 'consul_encryption_key' is undefined. 'consul_encryption_key' is undefined
fatal: [10.1.20.41]: FAILED! => changed=false 
  msg: 'AnsibleUndefinedVariable: ''consul_encryption_key'' is undefined. ''consul_encryption_key'' is undefined'
```

I am also getting:

`The error was: 'consul_agent_token' is undefined. 'consul_agent_token' is undefined`
The relevant line in the code shows ` regexp: '#agent = "<WILL BE FILLED LATER>"'`

**Comment by chrisvanmeer** [comment]
Hi there, did you run this with the Multipass or the Terraform workflow?  
I think I might know where this is coming from, but would like to verify first.

**Comment by vacquah** [comment]
Hi Chris - I already had existing VMs setup for this so skipped the infra provision stage and went straight to the 01 playbook and worked my way from there.  01/02 playbooks working ok. In 02, I commented out the reference to multipass and vault ( since I am installing just consul and nomad )

**Comment by chrisvanmeer** [comment]
Got it, I will look into this.

**Comment by chrisvanmeer** [comment]
I think your problem would be that the name of the servers (`hostnamectl`) do not correspond with the names in inventory you created within the servers group. Therefore a `when` condition will not be set to true when creating the Consul CA, thus failing to set a Consul encryption key.  
  
Yes, there was a typo in the file, but at least it was a consistent typo throughout the whole repository. I will correct this typo in the near future.  
  
However, using this repository other than the installation methods I provided and editing the playbooks kind of makes it impossible for me to guess what goes wrong. When I deploy the stack here on Multipass, the playbook finishes without any errors.

**Comment by vacquah** [comment]
Can I modify the when condition to match my server names?  Can you point me to the line where the relevant condition is?

**Comment by chrisvanmeer** [comment]
Line 72. But you are on your own from there on. Good luck!

**Comment by vacquah** [comment]
you mean this?

```
                  when:
                    - inventory_hostname in groups['servers']
```

My inventory hosts group is also called servers.  Is it looking for specific hostnames in the server group? Not sure why this should be the issue?  it seems to be looking for a definition for  consul_encryption_key:  but its not defined anywhere.

Anyway, thanks
